services:
  pma-db:
    container_name: pma-db
    image: postgres:16.1-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DB}
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  app-data:

networks:
  network:
    driver: bridge
