definitions:
  domain.Post:
    properties:
      caption:
        type: string
      content:
        type: string
      created_at:
        type: string
      deadline_after_revision:
        type: string
      deadline_before_revision:
        type: string
      design_link:
        type: string
      id:
        type: integer
      platforms:
        type: string
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
      upload_date:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/posts:
    get:
      consumes:
      - application/json
      description: Get All Posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Post'
            type: array
      security:
      - BearerAuth: []
      summary: Get All Posts
      tags:
      - Posts
  /api/posts/{id}:
    get:
      consumes:
      - application/json
      description: Get Post By Id
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Post'
      security:
      - BearerAuth: []
      summary: Get Post By Id
      tags:
      - Posts
swagger: "2.0"
